#!/usr/bin/env bash
# ============================================================
#  MOSAIC — Install Script
#  Usage:  sudo ./install.sh
#          mosaic start
#          mosaic status
#          mosaic benchmark
# ============================================================
set -euo pipefail

# ── Colour helpers ───────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; CYN='\033[0;36m'
YLW='\033[1;33m'; BLD='\033[1m';    RST='\033[0m'
ok()   { echo -e "${GRN}${BLD}  ✓${RST}  $*"; }
info() { echo -e "${CYN}     $*${RST}"; }
warn() { echo -e "${YLW}  ⚠  $*${RST}"; }
die()  { echo -e "${RED}  ✗  $*${RST}"; exit 1; }

MOSAIC_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_PREFIX="${INSTALL_PREFIX:-/usr/local}"
BIN_DIR="${INSTALL_PREFIX}/bin"
LIB_DIR="${INSTALL_PREFIX}/lib/mosaic"
DATA_DIR="${MOSAIC_HOME}/data"
LOG_DIR="${DATA_DIR}/logs"

echo ""
echo -e "${CYN}${BLD}"
echo "  ███╗   ███╗ ██████╗ ███████╗ █████╗ ██╗ ██████╗"
echo "  ████╗ ████║██╔═══██╗██╔════╝██╔══██╗██║██╔════╝"
echo "  ██╔████╔██║██║   ██║███████╗███████║██║██║"
echo "  ██║╚██╔╝██║██║   ██║╚════██║██╔══██║██║██║"
echo "  ██║ ╚═╝ ██║╚██████╔╝███████║██║  ██║██║╚██████╗"
echo "  ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝ ╚═════╝"
echo -e "${RST}"
echo "  Multi-Objective Scheduler — Disaster-Response Edge"
echo "  Installer v1.0"
echo ""

# ── Root check ───────────────────────────────────────────────
if [[ $EUID -ne 0 ]] && [[ "${INSTALL_PREFIX}" == "/usr/local" ]]; then
    warn "Not running as root. Will install to ~/.local instead."
    BIN_DIR="${HOME}/.local/bin"
    LIB_DIR="${HOME}/.local/lib/mosaic"
    mkdir -p "${BIN_DIR}" "${LIB_DIR}"
fi

# ── Python check ─────────────────────────────────────────────
echo -e "${BLD}[1/6] Checking Python...${RST}"
if ! command -v python3 &>/dev/null; then
    die "Python 3.9+ required. Install: sudo apt install python3"
fi
PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJ=$(echo "$PY_VER" | cut -d. -f1)
PY_MIN=$(echo "$PY_VER" | cut -d. -f2)
if [[ $PY_MAJ -lt 3 ]] || { [[ $PY_MAJ -eq 3 ]] && [[ $PY_MIN -lt 9 ]]; }; then
    die "Python 3.9+ required (found $PY_VER)"
fi
ok "Python $PY_VER"

# ── Optional deps ────────────────────────────────────────────
echo -e "${BLD}[2/6] Checking optional dependencies...${RST}"
if python3 -c "import matplotlib" 2>/dev/null; then
    ok "matplotlib — PNG chart generation enabled"
else
    warn "matplotlib not found — ASCII charts only. Install: pip3 install matplotlib"
fi

if command -v docker &>/dev/null; then
    ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
else
    info "Docker not found — container mode unavailable (optional)"
fi

if command -v gcc &>/dev/null; then
    ok "GCC $(gcc --version | head -1 | awk '{print $NF}') — hardware profiler can be built"
else
    warn "GCC not found — hardware profiler disabled. Install: sudo apt install gcc"
fi

# ── Build profiler ───────────────────────────────────────────
echo -e "${BLD}[3/6] Building hardware profiler...${RST}"
if command -v gcc &>/dev/null && [[ -f "${MOSAIC_HOME}/profiler/profiler.c" ]]; then
    if make -C "${MOSAIC_HOME}/profiler/" -s 2>/dev/null; then
        ok "Hardware profiler built: profiler/profiler"
    else
        warn "Profiler build failed — scheduler still works without it"
    fi
else
    info "Skipping profiler build (no GCC)"
fi

# ── Data directories ─────────────────────────────────────────
echo -e "${BLD}[4/6] Creating runtime directories...${RST}"
mkdir -p "${DATA_DIR}" "${LOG_DIR}" "${MOSAIC_HOME}/results"
touch "${DATA_DIR}/.gitkeep"
ok "Runtime dirs: ${DATA_DIR}"

# ── Initialise fingerprint database ─────────────────────────
echo -e "${BLD}[5/6] Initialising fingerprint database...${RST}"
cd "${MOSAIC_HOME}"
if python3 profiler/build_db.py --matrix &>/dev/null 2>&1; then
    ok "Fingerprint DB initialised: data/fingerprints.db"
else
    warn "DB init failed — will retry on first mosaic start"
fi

# ── Install mosaic CLI ───────────────────────────────────────
echo -e "${BLD}[6/6] Installing mosaic CLI...${RST}"

CLI_PATH="${BIN_DIR}/mosaic"

cat > "${CLI_PATH}" << CLIEOF
#!/usr/bin/env bash
# MOSAIC CLI — auto-generated by install.sh
MOSAIC_HOME="${MOSAIC_HOME}"
DATA_DIR="${MOSAIC_HOME}/data"
SOCK="${MOSAIC_HOME}/data/mosaic.sock"
PID_FILE="${MOSAIC_HOME}/data/mosaic.pid"
LOG_FILE="${MOSAIC_HOME}/data/logs/scheduler.log"

RED='\033[0;31m'; GRN='\033[0;32m'; CYN='\033[0;36m'
YLW='\033[1;33m'; BLD='\033[1m'; RST='\033[0m'
ok()   { echo -e "\${GRN}\${BLD}  ✓\${RST}  \$*"; }
info() { echo -e "\${CYN}     \$*\${RST}"; }
warn() { echo -e "\${YLW}  ⚠  \$*\${RST}"; }
err()  { echo -e "\${RED}  ✗  \$*\${RST}"; }

is_running() { [[ -S "\${SOCK}" ]] && [[ -f "\${PID_FILE}" ]]; }

cmd_start() {
    local POWER_CAP="\${1:-85}"
    if is_running; then
        warn "MOSAIC already running (PID=\$(cat \$PID_FILE))"
        return 0
    fi
    mkdir -p "\${DATA_DIR}/logs"
    echo -e "\${BLD}Starting MOSAIC scheduler (power_cap=\${POWER_CAP}W)...\${RST}"
    python3 "\${MOSAIC_HOME}/scheduler/scheduler.py" \\
        --power-cap "\${POWER_CAP}" \\
        >> "\${LOG_FILE}" 2>&1 &
    echo \$! > "\${PID_FILE}"
    # Wait for socket
    for i in \$(seq 1 30); do
        [[ -S "\${SOCK}" ]] && break
        sleep 0.3
    done
    if [[ -S "\${SOCK}" ]]; then
        ok "MOSAIC started  PID=\$(cat \${PID_FILE})  socket=\${SOCK}"
        info "Dashboard: mosaic dashboard"
        info "Logs:      tail -f \${LOG_FILE}"
    else
        err "Scheduler failed to start. Check: \${LOG_FILE}"
        return 1
    fi
}

cmd_stop() {
    if ! is_running; then
        warn "MOSAIC not running"
        return 0
    fi
    PID=\$(cat "\${PID_FILE}")
    kill "\${PID}" 2>/dev/null && ok "MOSAIC stopped (PID=\${PID})" || err "Kill failed"
    rm -f "\${PID_FILE}" "\${SOCK}"
}

cmd_status() {
    if ! is_running; then
        warn "MOSAIC not running. Start with: mosaic start"
        return 1
    fi
    python3 "\${MOSAIC_HOME}/scheduler/client.py" status 2>/dev/null || err "Status query failed"
}

cmd_benchmark() {
    local PATTERN="\${1:-burst}"
    local RATE="\${2:-6}"
    local DURATION="\${3:-60}"
    echo -e "\${BLD}Running benchmark: pattern=\${PATTERN} rate=\${RATE}/s duration=\${DURATION}s\${RST}"
    cd "\${MOSAIC_HOME}"
    python3 run_experiment.py --compare all \\
        --pattern "\${PATTERN}" --rate "\${RATE}" --duration "\${DURATION}"
}

cmd_demo() {
    echo -e "\${BLD}Starting MOSAIC demo...\${RST}"
    cmd_start 85
    sleep 1
    echo -e "\${BLD}Running disaster scenario workload (30s)...\${RST}"
    cd "\${MOSAIC_HOME}"
    python3 workload-gen/workload_gen.py \\
        --pattern disaster --rate 5 --duration 30 \\
        --scheduler --quiet
    cmd_status
}

cmd_dashboard() {
    local PORT="\${1:-7777}"
    echo -e "\${BLD}Starting live telemetry dashboard on http://localhost:\${PORT}\${RST}"
    cd "\${MOSAIC_HOME}"
    python3 dashboard/server.py --port "\${PORT}"
}

cmd_logs() {
    tail -f "\${LOG_FILE}" 2>/dev/null || { err "No log file yet. Run: mosaic start"; return 1; }
}

cmd_classify() {
    cd "\${MOSAIC_HOME}"
    python3 run_experiment.py --classify \\
        --ipc "\${1:-2.1}" --llc "\${2:-0.18}" --bw "\${3:-8.5}" --br "\${4:-0.06}"
}

cmd_test() {
    echo -e "\${BLD}Running MOSAIC test suite...\${RST}"
    cd "\${MOSAIC_HOME}"
    python3 tests/test_all.py
}

cmd_help() {
    echo ""
    echo -e "  \${BLD}mosaic\${RST} — Multi-Objective Scheduler for AI-Cloud Inference Colocation"
    echo ""
    echo "  Commands:"
    echo "    start [power_cap_watts]     Start the scheduler daemon (default cap: 85W)"
    echo "    stop                        Stop the scheduler daemon"
    echo "    status                      Show live metrics"
    echo "    benchmark [pattern] [rate] [duration]  Run 5-scheduler comparison"
    echo "    demo                        Full demo: start + workload + status"
    echo "    dashboard [port]            Live telemetry dashboard (default port: 7777)"
    echo "    logs                        Tail scheduler logs"
    echo "    classify [ipc] [llc] [bw] [br]  ML-classify a workload fingerprint"
    echo "    test                        Run test suite (63 tests)"
    echo "    help                        Show this message"
    echo ""
    echo "  Examples:"
    echo "    mosaic start 90"
    echo "    mosaic benchmark disaster 8 120"
    echo "    mosaic dashboard 8080"
    echo "    mosaic classify 1.8 0.42 28.0 0.08"
    echo ""
}

CMD="\${1:-help}"
shift 2>/dev/null || true
case "\${CMD}" in
    start)     cmd_start "\$@" ;;
    stop)      cmd_stop ;;
    status)    cmd_status ;;
    benchmark) cmd_benchmark "\$@" ;;
    demo)      cmd_demo ;;
    dashboard) cmd_dashboard "\$@" ;;
    logs)      cmd_logs ;;
    classify)  cmd_classify "\$@" ;;
    test)      cmd_test ;;
    help|--help|-h) cmd_help ;;
    *) err "Unknown command: \${CMD}"; cmd_help; exit 1 ;;
esac
CLIEOF

chmod +x "${CLI_PATH}"
ok "CLI installed: ${CLI_PATH}"

# ── PATH check ───────────────────────────────────────────────
if ! echo "$PATH" | grep -q "${BIN_DIR}"; then
    warn "${BIN_DIR} is not in your PATH"
    info "Add to ~/.bashrc or ~/.zshrc:"
    info "  export PATH=\"${BIN_DIR}:\$PATH\""
    info "Then: source ~/.bashrc"
fi

# ── perf_event check ─────────────────────────────────────────
PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo "unknown")
if [[ "$PARANOID" != "unknown" ]] && [[ "$PARANOID" -gt 1 ]]; then
    warn "perf_event_paranoid=$PARANOID — hardware counters need ≤1"
    info "Enable: sudo sysctl -w kernel.perf_event_paranoid=1"
fi

echo ""
echo -e "${GRN}${BLD}  MOSAIC installed successfully!${RST}"
echo ""
echo "  Quick start:"
echo -e "    ${BLD}mosaic demo${RST}              — full demo in one command"
echo -e "    ${BLD}mosaic start${RST}             — start the scheduler daemon"
echo -e "    ${BLD}mosaic benchmark${RST}         — compare all 5 schedulers"
echo -e "    ${BLD}mosaic dashboard${RST}         — live telemetry dashboard"
echo -e "    ${BLD}mosaic help${RST}              — all commands"
echo ""
